package com.chamalo.mbdream.DTO;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Class for request when you want to add a Moto
 *
 * @author Chamalo
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class MotoRequest {
    // No slug, he's generated by service
    private Long idMoto;

    private String nomMoto;

    private Integer prixMoto;

    private String descriptionMoto;

    private boolean isFeatured;

    private Long marqueId;

    private Long categorieId;
}
